exam/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
app_name = 'onlineexam'

urlpatterns = [
    # url(r'^', views.index, name='index')
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create/$', views.Objective_exam_create_View, name='create_exam'),
    url(r'^submit/$', views.Objective_exam_submit_View, name='submit_question'),
    # url(r'^exam-created/(?P<exam_id>\d+)/$', TemplateView.as_view(), name='submit_success'),
    url(r'^result/$', views.Result_View.as_view(), name='view_result'),
    url(r'^search/$', views.Search_View.as_view(), name='search_exam_page'),
    url(r'^search_ajax/$', views.search_exam_ajax, name='search_exam'),
    url(r'^(?P<exam_id>\d+)/objective/$', views.Objective_exam_View.as_view(), name='Exam'),
    url(r'^sendEmail/$', views.Send_email, name='send_email'),
    url(r'^login/$', views.login_auth, name='login'),
    # url(r'^login/$', "django.contrib.auth.views.login", name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.register_user, name='register'),
    url(r'^forget-password/$', views.forget_password, name='forget_password'),
    path('exam/<str:exam_id>', views.Exam_View.as_view(), name='student_exam'),
    path('submit-exam', views.Student_Exam_submit.as_view(), name='student_exam_submit'),
    path('result/<id>', views.Student_Result.as_view(), name='student_result'),
    url(r'^', include('user.urls'))
]

onlineexam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('exam.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/createonlineexam/error.html
oops error

templates/createonlineexam/exam_create_success.html
{% extends "layout.html" %}

{% block content %}
{% load staticfiles %}
<div class="container">
    <div class="message-block">
        <p>Your Exam Id is <b>{{ exam_id }}</b></p>
        <p>Below is the exam link:</br>

            <a href="">
                {{ request.scheme }}:{{ request.META.HTTP_HOST }}{% url 'onlineexam:student_exam' exam_id %}
            </a>
        </p>
    </div>

</div>

{% endblock %}

templates/createonlineexam/exam_result.html
{% extends "layout.html" %}

{% block content %}
{% load staticfiles %}
<div class="container">
    <div class="message-block">
        <p>Hello, <b>{{ result.name }}</b></p>
        <p>Your score is:</br>
            {{result.score}} %
        </p>
    </div>

</div>

{% endblock %}

templates/createonlineexam/login.html
{% extends "layout.html" %}

{% block content %}
{% load staticfiles %}
<div class="col-sm-4"></div>
<div class="col-sm-4">
    <form action="{% url 'onlineexam:login' %}" method="post" id="loginForm" onsubmit="return loginValidate(this);" >
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        <div class="form-header text-center">Login</div>
        <div id="div-login-msg">
            <span id="error1" class="hidden"></span>
        </div>

        <div class="form-group has-feedback" id="email-box">
            <input type="text" class="form-control" id="logInEmail" name="logInEmail" placeholder="Email"
                   onblur="validate('logInEmail','email-box');">
            <span class="form-control-feedback glyphicon glyphicon-user"></span>
            <span id="loginEmailError" class="hidden"></span>
        </div>
        <div class="form-group has-feedback" id="password-box">
            <input type="password" class="form-control" id="logInPassword" name="logInPassword" placeholder="Password"
                   onblur="validate('logInPassword','password-box');">
            <span class="form-control-feedback glyphicon glyphicon-eye-open"></span>
            <span id="loginPwdError" class="hidden"></span>
        </div>
        <div class="form-group">
            <label for="remember" class="btn-link">
                <input type="checkbox" name="remember" id="remember"> Remember me
            </label>
        </div>

        <div class="form-group">
            <div>
                <button type="submit" class="btn btn-primary btn-lg btn-block">Login</button>
            </div>
            <div>
                {% comment %}<button id="login_lost_btn" type="button" class="btn btn-link">Lost Password?</button>
                <button id="login_register_btn" type="button" class="btn btn-link">Register</button>{% endcomment %}
            </div>
        </div>
    </form>
</div>
{% endblock %}

templates/createonlineexam/objective_create.html
{% extends "layout.html" %}

{% block content %}

<a type="button" id="help-me" href="#" role="button" data-toggle="modal" data-target="#help" class="help"></a>
<div class="container" >
<form class="form-horizontal" id="objective-exam-create-form" action = "{% url 'onlineexam:submit_question'%}" method = 'post'>
    <article id = "apage_1" class="info-container text-center">
        {% csrf_token %}
        <h2 class="text-center">Create Exam</h2>
        <span id="errormsg" class="hidden"></span>
        <div class="form-group">
{#                <label class="col-md-3" for="name"> Name * </label>#}
            <div class="col-md-12 text-left">
                <input type="textbox" id="name" class="form-control" name="name" maxlength="50" placeholder="Enter Your Name" required>
            </div>
        </div>
        <div class="form-group">
{#                <label class="col-md-3" for="name"> Name * </label>#}
            <div class="col-md-12 text-left">
                <input type="email" id="mailid" class="form-control" name="mailid" maxlength="50" placeholder="Enter Your Email Id" required>
            </div>
        </div>
        <div class="form-group">
{#                <label class="col-md-3" for="examname"> Exam Name * </label>#}
            <div class="col-md-12 text-left">
                <input type="textarea" id="examname" class="form-control" name="examname" maxlength="150" placeholder="Enter Exam Name" required>
            </div>
        </div>
        <div class="form-group">
{#                <label class="col-md-3" for="phonenumber">Phone Number * </label>#}
            <div class="col-md-12 text-left">
                <input type="textarea" id="phonenumber" class="form-control" name="phonenumber" maxlength="12" placeholder="Enter Phone Number" required><br>
            </div>
        </div>
    </article>
    <article id= "apage2" class="container-effect">
        {% include '../objective_exam_layout.html' %}
    </article>
</form>
</div>
<div class="modal fade" id="help" tabindex="-1" role="form" aria-labelledby="help">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title text-center">Help To Create Objective Exam </h4>
            </div>
            <div class="modal-body">
                <p>Please fill all the values asked on the first page, as they all are mandatory fields and you will not allow to move to the second page.
                </p><p>Your Email id will be saved and use for communication purpose, so be sure you are providing the correct email id.</p>
                <p>Exam name is the name which will appear as the heading of the exam to the student and it will also use in future to search exam by name.</p>
                <p>We store phone number for future preference.</p>
                <p>After filling all these details click on the <b>NEXT</b> button it will direct you to the main exam creation page.</p>
                <p>This page will have 10 questions and each question will have<b> 4 options</b> which will be given as choice to the student.</p>
                <p>This page also have one more field name <b>Correct Answer</b>. Here you need to write the correct answer.<b> Please do not write
                    the option number </b>as it will give you the wrong result. You need to write the complete answer in <b>Correct Answer</b> filed.</p>
                <p>Default time limit for the exam is <b>20 min</b>. We are working on it, in future you will be allow to choose the time limit of the exam.This feature
                will come on the next release.</p>
                <p>The result will be auto calculated by the system and the score will be send to you at your email address and you can also view all the result
                in result tab on the <a href="http://createonlineexam.com">home page</a>.</p>
                <p>After successful Exam Creation, A Email with all the details will be sent to your email id.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>
{% endblock %}

templates/createonlineexam/objective_exam.html
{% extends "createonlineexam/../layout.html" %}

{% block content %}


{% endblock %}

templates/createonlineexam/result_display.html
{% extends "layout.html" %}

{% block content %}
{% include '../result_display_layout.html' %}
{% endblock %}

templates/createonlineexam/search_result.html
{% extends "layout.html" %}

{% block content %}
    <div class="container">
        <section id="search-exam">
            <div class="input-group col-sm-12 col-lg-12 col-md-12">
                <form id="search_form" class="form-horizontal" method="get" autocomplete="off" onsubmit="return inputCheck(this)">
                    {% csrf_token %}
                    <input type="text" name="examName" id="examName" class="form-control" placeholder="Search For Exam" value="">
                    <a type="submit"><span class="glyphicon glyphicon-search form-control-feedback"></span></a>
                </form>
                <div id="searchResults" class="searchResult"></div>
            </div>
        </section>
        <section>

<!--    {% if search_result %}-->
            {{search_result | safe}}
<!--        {% for ques in search_result %}-->
<!--            {{ques | safe }}-->
<!--        {% endfor %}-->
<!--    {{ search_result }}-->

    {% endif %}
        </section>
    </div>
{% endblock %}

templates/createonlineexam/student_exam.html
{% extends "layout.html" %}

{% block content %}

<div class="container">
    <form action="{% url 'onlineexam:student_exam_submit' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="exam_id" value="{{questions.0}}">
        <div class="row form-group student-info">
            <div class="col-md-4">
                <label>Email id</label>
                <input type="text" class="form-control" name="student_email" required>
            </div>
            <div class="col-md-4">
                <label>Name</label>
                <input type="text" class="form-control" name="student_name" required>
            </div>
            <div class="col-md-4">
                <label>Phone No</label>
                <input type="text" class="form-control" name="student_phone_no" required>
            </div>
        </div>
        {% for question in questions.1 %}
        <div class="question-blk">
            <div class="row form-group">
                <div class="col-sm-1">Ques {{ question.ques.question_number }}.</div>
                <div class="col-sm-11">{{ question.ques }}</div>
            </div>
            <div class="row form-check">
                <div class="col-sm-1">Ans</div>

                {% for ans in question.ans %}
                    <div class="col-sm-11">
                        <div class="row">
                            <div class="col-sm-6">
                                <input type="radio" class="form-check-input" value="{{ ans.fields.choice_1 }}" name="ans{{ ans.fields.question_number }}">
                                <label class="form-check-label">{{ ans.fields.choice_1 }}</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="radio" class="form-check-input" value="{{ ans.fields.choice_2 }}" name="ans{{ ans.fields.question_number }}">
                                <label class="form-check-label">{{ ans.fields.choice_2 }}</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <input type="radio" class="form-check-input" value="{{ ans.fields.choice_3 }}" name="ans{{ ans.fields.question_number }}">
                                <label class="form-check-label">{{ ans.fields.choice_3 }}</label>
                            </div>
                            <div class="col-sm-6">
                                <input type="radio" class="form-check-input" value="{{ ans.fields.choice_4 }}" name="ans{{ ans.fields.question_number }}">
                                <label class="form-check-label">{{ ans.fields.choice_4 }}</label>
                            </div>
                        </div>
                    </div>

                {% endfor %}

            </div>
        </div>

        {% endfor %}
        <div class="text-center">
            <button type="submit" class="btn btn-success btn-lg" >Submit</button>
        </div>

    </form>
</div>


<script>
$(document).ready(function(){
   $(document).bind("contextmenu",function(e){
      return false;
   });
});
</script>
{% endblock %}

templates/createonlineexam/submit_ques.html
{% extends "layout.html" %}

{% block content %}

{% endblock %}