exam/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
app_name = 'onlineexam'

urlpatterns = [
    # url(r'^', views.index, name='index')
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create/$', views.Objective_exam_create_View, name='create_exam'),
    url(r'^submit/$', views.Objective_exam_submit_View, name='submit_question'),
    # url(r'^exam-created/(?P<exam_id>\d+)/$', TemplateView.as_view(), name='submit_success'),
    url(r'^result/$', views.Result_View.as_view(), name='view_result'),
    url(r'^search/$', views.Search_View.as_view(), name='search_exam_page'),
    url(r'^search_ajax/$', views.search_exam_ajax, name='search_exam'),
    url(r'^(?P<exam_id>\d+)/objective/$', views.Objective_exam_View.as_view(), name='Exam'),
    url(r'^sendEmail/$', views.Send_email, name='send_email'),
    url(r'^login/$', views.login_auth, name='login'),
    # url(r'^login/$', "django.contrib.auth.views.login", name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.register_user, name='register'),
    url(r'^forget-password/$', views.forget_password, name='forget_password'),
    path('exam/<str:exam_id>', views.Exam_View.as_view(), name='student_exam'),
    path('submit-exam', views.Student_Exam_submit.as_view(), name='student_exam_submit'),
    path('result/<id>', views.Student_Result.as_view(), name='student_result'),
    url(r'^', include('user.urls'))
]

onlineexam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('exam.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/exam_create_success_layout.html
<div class="container">
    <div class="message-block">
        <p>Your Exam Id is <b>{{ exam_id }}</b></p>
        <p>Below is the exam link:</br>

            <p class="copy_text" onclick="copy('new_exam_id')" id="new_exam_id">
                {{ request.scheme }}:{{ request.META.HTTP_HOST }}{% url 'onlineexam:student_exam' exam_id %}
            </p>
        </p>
    </div>

</div>

templates/footer.html
<!-- Latest compiled and minified JavaScript -->
{% load staticfiles %}
{#<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>#}
<script scr="{% static "createonlineexam/js/jquery.lazyload.min.js" %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js"></script>
<script src="{% static "createonlineexam/js/jquery.form.js" %}"></script>
<script src="{% static "createonlineexam/js/bootstrap.min.js" %}"></script>
<!--validate script to validate form-->
<script src="{% static "createonlineexam/js/Validation.js" %}"></script>
<script src="{% static "createonlineexam/js/script.js" %}"></script>
<script src="{% static "createonlineexam/js/notify.js" %}"></script>
<script src="{% static "createonlineexam/js/paging.js" %}"></script>
<script src="{% static "script.js" %}"></script>


<script type="text/javascript">
    function goBack() {
        window.history.back();
    }

</script>

<a href="#create-exam" class="scrollToTop"><img src="{% static "createonlineexam/images/top.png" %}" height="40" width="40"></a>
<footer class="text-center">

    <div id="footer" class="footer">

        <p>All Rights Reserved</p>
    </div>
</footer>

templates/header.html
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Create Online Exam for your students!!">
    <meta name="keywords" content="Create Online Exam, Objective exam, get result generated automatically">
    <meta name="author" content="Rajesh Upadhayaya">
    {% load staticfiles %}
{#    {% collectstatic %}#}
    <link rel="icon" type="image/ico" href="{% static "/createonlineexam/images/favicon.ico" %}">
    <title>Create Online Exam</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="{% static "/createonlineexam/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "/createonlineexam/css/bootstrap.min.css" %}">
    <!-- Optional theme -->
    <link rel="stylesheet" href="{% static "/createonlineexam/css/bootstrap-theme.min.css" %}">
    <!--Modified personal css-->
    <link rel="stylesheet" type="text/css" href="{% static "/createonlineexam/css/style.css" %}">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Crimson+Text:600' rel='stylesheet' type='text/css'>
    <script src="{% static "createonlineexam/js/jquery-2.1.4.min.js" %}"></script>
</head>

templates/layout.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<html>

    {% include 'header.html' %}
    {% url 'onlineexam:index' as url %}
    {% if request.path == url %}
        <nav class="navbar navbar-default navbar-fixed-top" id="main-nav">
            <div class = "container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="#navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a href="{% url 'onlineexam:index' %}" class="navbar-brand">C O E</a>
                </div>

                <div class="collapse navbar-collapse" id="navbar">
                    <a type="button" id="modal_trigger" href="#" role="button" data-toggle="modal" data-target="#login-modal" class="btn navbar-btn btn-warning navbar-right">Login/Register</a>
                    <ul class="nav navbar-nav nav-pills">
                        <li class="active"> <a href="#create-exam"> Create Exam </a></li>
                        <li class=""> <a href="#searchExam"> Search Exams </a></li>
                        <li class=""> <a href="#contact"> Contact </a></li>
                    </ul>
                </div>
            </div>
        </nav>
    {% else %}
        {% include 'navbar.html' %}
    {% endif %}
    <body>
    {% block content %}
    {% endblock %}
    {% include 'footer.html' %}
    </body>
</html>

templates/navbar.html
<nav class="navbar navbar-default navbar-fixed-top" id="main-nav">
    <div class = "container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="{% url 'onlineexam:index' %}" class="navbar-brand">C O E</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <a type="button" id="modal_trigger" href="#" role="button" data-toggle="modal" data-target="#login-modal" class="btn navbar-btn btn-warning navbar-right">Login/Register</a>
        </div>
    </div>
</nav>

templates/objective_exam_layout.html
    {% for i in loop_times %}
        <div class="quest-block">
            <div class="row">
                <div class="col-md-1">
                    <label class="text-left" for="ques{{ i }}">Ques {{ i }}.</label>
                </div>

                <div class="col-md-11">
                    <textarea name="ques{{ i }}" class="form-control" maxlength="500" required></textarea><br>
                </div>
            </div>

            <div class="row">
                <div class="col-md-1">
                    <label class="text-left" for="ans{{ i }}">Ans. </label>
                </div>
                <div class="col-md-1">
                    <label class="text-left" for="ans{{ i }}a">A.</label>
                </div>

                <div class="col-md-4 text-left">
                    <input type="textarea" class="form-control" name="ans{{ i }}a" class="textbox1" maxlength="100" required>
                </div>
                <div class="col-md-1 ">
                    <label class=" text-right" for="ans{{ i }}b">B.</label>
                </div>
                <div class="col-md-5 text-left ">
                    <input type="textarea" class="form-control" name="ans{{ i }}b" class="textbox1" maxlength="100" required><br>
                </div>
            </div>

            <div class="row">
                <div class="col-md-1">
                    <label class=" text-left"></label>
                </div>
                <div class="col-md-1">
                    <label class="text-left" for="ans{{ i }}c">C.</label>
                </div>
                <div class="col-md-4 text-left">
                    <input type="textarea" class="form-control" name="ans{{ i }}c" maxlength="100" required>
                </div>
                <div class="col-md-1">
                    <label class="text-right" for="ans{{ i }}d">D.</label>
                </div>
                <div class="col-md-5 text-left">
                    <input type="textarea" class="form-control" name="ans{{ i }}d" maxlength="100" required><br>
                </div>
            </div>
            <div class="row">
                <div class="col-md-2 ">
                    <label class="text-left" for="ans{{ i }}correct"> Correct Answer:</label>
                </div>
                <div class="col-md-10 text-left ">
                    <input type="textarea" class="form-control" name="ans{{ i }}correct" maxlength="100" required><br><br>
                </div>
            </div>
        </div>
    {% endfor %}
    <div class="text-right">
        <input type='submit' class="btn btn-success btn-lg text-right" value= 'Create Exam' name='objsubmit'>
    </div>

templates/result_display_layout.html
<a type="button" id="help-me" href="#" role="button" data-toggle="modal" data-target="#help" class="help"></a>
<div class="container">
    <div class="jumbotron">
        <form class="form-horizontal" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="Exam Id">Exam Id:</label>
                <input type="text" class="form-control" name="exam_id" id="exam_id" value="{{exam_id}}"
                       placeholder="Please provide your Exam Id" required>
            </div>

            <button type="submit" value="View Result" class="btn btn-info">View Result</button>


        </form>
    </div>
    {% if results %}
    <div class="result-block">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>S.No</th>
                    <th>Name</th>
                    <th>Exam Date</th>
                    <th>Score</th>
                </tr>
            </thead>
            <tbody>

            {% for result in results %}
                <tr>
                    <th>{{forloop.counter}}</th>
                    <td>{{result.name}}</td>
                    <td>{{result.exam_date}}</td>
                    <td>{{result.score}}</td>
                </tr>

            {% endfor %}
            </tbody>
        </table>
    </div>
    {% endif %}
</div>



<div class="modal fade" id="help" tabindex="-1" role="form" aria-labelledby="help">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title text-center">How to Search Exam Result </h4>
            </div>
            <div class="modal-body">
                <p>Please provide the exam id in <b> EXAM ID </b> field. This id was provided during the creation  of exam and the same was share
                    with you with e-mail.
                <p>Please refer your email for exam id.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal">Close</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>