exam/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
app_name = 'onlineexam'

urlpatterns = [
    # url(r'^', views.index, name='index')
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^create/$', views.Objective_exam_create_View, name='create_exam'),
    url(r'^submit/$', views.Objective_exam_submit_View, name='submit_question'),
    # url(r'^exam-created/(?P<exam_id>\d+)/$', TemplateView.as_view(), name='submit_success'),
    url(r'^result/$', views.Result_View.as_view(), name='view_result'),
    url(r'^search/$', views.Search_View.as_view(), name='search_exam_page'),
    url(r'^search_ajax/$', views.search_exam_ajax, name='search_exam'),
    url(r'^(?P<exam_id>\d+)/objective/$', views.Objective_exam_View.as_view(), name='Exam'),
    url(r'^sendEmail/$', views.Send_email, name='send_email'),
    url(r'^login/$', views.login_auth, name='login'),
    # url(r'^login/$', "django.contrib.auth.views.login", name='login'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^register/$', views.register_user, name='register'),
    url(r'^forget-password/$', views.forget_password, name='forget_password'),
    path('exam/<str:exam_id>', views.Exam_View.as_view(), name='student_exam'),
    path('submit-exam', views.Student_Exam_submit.as_view(), name='student_exam_submit'),
    path('result/<id>', views.Student_Result.as_view(), name='student_result'),
    url(r'^', include('user.urls'))
]

onlineexam/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^', include('exam.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf.urls import url, include
from django.urls import path
from . import views
from django.views.generic import TemplateView
from user import views as users
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    url(r'^dashboard/$', users.DashboardView, name='dashboard'),
    url(r'^profile/$', login_required(users.ProfileView.as_view()), name='profile'),
    url(r'^uploadphoto/$', login_required(users.ProfileView.as_view()), name='uploadphoto'),
    url(r'^user/all_exams/$', login_required(users.AllExams.as_view()), name='all_exams'),
    url(r'^user/new_exam/$', login_required(users.CreateNewExam.as_view()), name='new_exam'),
    url(r'^user/submit_create_exam/$', login_required(users.SubmitCreateNewExam.as_view()), name='submit_create_exam'),
    url(r'^user/check_result/$', login_required(users.Result_View.as_view()), name='check_result')
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.views import View
from django.core.files.storage import FileSystemStorage
import datetime
from django.shortcuts import redirect
from django.contrib import messages
from exam.models import Question, Answers, ExamCreateDetails, Account, Exam_Result
from django.db.models import Count
from exam.serializers import AccountSerializer
# Create your views here.

num_range = 2

@login_required
def DashboardView(request):
    examcreateddetails = ExamCreateDetails.objects.filter(email_id=request.user).count()
    examsubmitted = ExamCreateDetails.objects.filter(email_id=request.user).annotate(exam_submitted=Count('exam_result'))
    # print(examsubmitted[3].exam_submitted)
    return render(request, 'user/dashboard.html', context={'examcreateddetails':examcreateddetails})
    # if request.user.is_authenticated:
    #     return render(request, 'dashboard.html')
    # else:
    #     return render(request, 'createonlineexam/login.html')


class ProfileView(View):

    template_name = 'user/profile.html'

    def get(self,request):

        return render(request, self.template_name)

    def post(self,request):

        user = Account.objects.get(pk=request.user.id)

        try:
            profile_pic = request.FILES['photo']
        except:
            profile_pic = False
        # user = Account.objects.get(pk=request.user.id)
        # print(user)

        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']

        if profile_pic:
            ext = profile_pic.name.split(".")[1].lower()
            img_name = 'IMG' + str(int(datetime.datetime.now().timestamp()))+'.'+ext
            fs = FileSystemStorage()
            fs.save(img_name, profile_pic)
            user.profile_pic = img_name

        try:
            user.save()
            messages.success(request, 'Profile details updates successfully')
        except:
            messages.error(request, 'Error on updating data')

        return redirect('onlineexam:profile')


class AllExams(generic.ListView):
    template_name = 'user/all_exams.html'
    context_object_name = 'exams'

    def get_queryset(self):
        return ExamCreateDetails.objects.filter(email_id=self.request.user)


class CreateNewExam(generic.TemplateView):
    template_name = 'user/create_exam.html'

    def get_context_data(self, **kwargs):
        context = super(CreateNewExam, self).get_context_data(**kwargs)
        context['loop_times'] = range(1, num_range+1)
        return context

class SubmitCreateNewExam(View):

    def post(self,request):
        exam_id = datetime.datetime.now().strftime("EX%y%m%d%H%M%S%f")
        username = request.user.first_name
        emailid = request.user
        examName = request.POST['examname']
        contact_no = 0
        examDuration = '00:20'
        exam_creation_time = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')

        # with transaction:
        examDetail_set = ExamCreateDetails(username=username, email_id=emailid, exam_create_date=exam_creation_time,
                                           exam_id=exam_id,
                                           exam_duration=examDuration, contact_no=contact_no, exam_name=examName)
        # try:
        examDetail_set.save()
        for i in range(1, num_range + 1):
            ques = request.POST['ques' + str(i)].strip()
            ansa = request.POST['ans' + str(i) + 'a'].strip()
            ansb = request.POST['ans' + str(i) + 'b'].strip()
            ansc = request.POST['ans' + str(i) + 'c'].strip()
            ansd = request.POST['ans' + str(i) + 'd'].strip()
            ansCorrect = request.POST['ans' + str(i) + 'correct'].strip()
            question_set = Question(question_number=i, question_text=ques, exam_id_id=exam_id,
                                    exam_create_date=exam_creation_time)
            answer_set = Answers(question_number=i, choice_1=ansa, choice_2=ansb, choice_3=ansc, choice_4=ansd,
                                 correct_choice=ansCorrect, exam_id_id=exam_id)
            # if(question_set.save() & answer_set.save() & examDetail_set.save()):
            #     return HttpResponseRedirect(reverse('createonlineexam:submit_success', args=(exam_id,)))
            question_set.save()
            answer_set.save()
        return render(request, 'user/exam_create_success.html', context={'exam_id': exam_id})

class Result_View(View):

    template_name = 'user/result_display.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        exam_id = request.POST['exam_id']
        results = Exam_Result.objects.filter(exam_id=exam_id)
        return render(request, self.template_name, context={'results': results, 'exam_id': exam_id})

templates/user/all_exams.html
{% extends "user/user_layout.html" %}

{% block content %}
{% load staticfiles %}

<div class="user-content">
    <h3>Welcome {{user.first_name}} {{user.last_name}}</h3>

    <table class="table table-striped">
        <thead>
            <th>S.No</th>
            <th>Exam Name</th>
            <th>Exam Id</th>
            <th>Exam Url</th>
            <th>Created On</th>
        </thead>
        {% for exam in exams %}
        <tr>
            <th>{{forloop.counter}}</th>
            <td>{{exam.exam_name}}</td>
            <td>{{exam.exam_id}}</td>
            <td onclick="copy('exam_id_{{forloop.counter}}')" title="Click to copy" class="copy_text" id="exam_id_{{forloop.counter}}">
                {{ request.scheme }}:{{ request.META.HTTP_HOST }}{% url 'onlineexam:student_exam' exam.exam_id %}</td>
            <td>{{exam.exam_create_date}}</td>
        </tr>
        {% endfor %}


    </table>
</div>
{% endblock %}

templates/user/create_exam.html
{% extends "user/user_layout.html" %}

{% block content %}
{% load staticfiles %}
<form class="form-horizontal" id="objective-exam-create-form" action = "{% url 'onlineexam:submit_create_exam'%}" method = 'post'>
    {% csrf_token %}
    <div class="quest-block">
        <div class="row">
            <div class="col-md-2">
                <label for="examname">Exam Name</label>
            </div>
            <div class="col-md-8">
                <input type="text" name="examname" class="form-control" id="examname">
            </div>
        </div>

    </div>


    {% include '../objective_exam_layout.html' %}
</form>

{% endblock %}

templates/user/dashboard.html
{% extends "user/user_layout.html" %}

{% block content %}
{% load staticfiles %}

<div class="user-content">
    <h3>Welcome {{user.first_name}} {{user.last_name}}</h3>
    <div class="row">
        <div class="col-md-6">
            <h5>My Stats</h5>
            <table class="table table-striped">
                <tr>
                    <td>No of Exam Created</td>
                    <td>{{examcreateddetails}}</td>
                </tr>
<!--                <tr>-->
<!--                    <td>No of Exam Submitted by Student</td>-->
<!--                    <td></td>-->
<!--                </tr>-->


            </table>
        </div>

    </div>

</div>
{% endblock %}

templates/user/exam_create_success.html
{% extends "user/user_layout.html" %}

{% block content %}
{% load staticfiles %}

{% include '../exam_create_success_layout.html' %}

{% endblock %}

templates/user/navbar_user.html
<nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
  <a class="navbar-brand" href="#">C O E</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse navbar-right" id="navbarNavDropdown">
    <ul class="navbar-nav">

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          {{user.get_username}}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'onlineexam:dashboard' %}">DashBoard</a>
            <a class="dropdown-item" href="{% url 'onlineexam:profile' %}">Profile</a>
            <a class="dropdown-item" href="{% url 'onlineexam:logout' %}">Logout</a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item" >Help</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

templates/user/profile.html
{% extends "user/user_layout.html" %}

{% block content %}
{% load staticfiles %}

<div class="user-content">
    {% if messages %}

        {% for message in messages %}
        <div class="alert {% if message.tags %} alert-{{ message.tags }} {% endif %} alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endfor %}
    {%endif%}

    <form id="upload-photo" method="POST" enctype="multipart/form-data" action="{% url 'onlineexam:uploadphoto'%}">
        {% csrf_token %}
        <div class="form-row">
            <div class="form-group col-md-3">
                <label for="first_name">First Name</label>
                <input type="text" class="form-control" name="first_name" id="first_name" value="{{user.first_name}}">
            </div>
            <div class="form-group col-md-3">
                <label for="last_name">Last Name</label>
                <input type="text" class="form-control" name="last_name" id="last_name" value="{{user.last_name}}">
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-3">
                <label for="photo">Profile Photo</label>
                <input type="file" class="form-control" name="photo" id="photo">

            </div>
        </div>
        <button type="submit" class="btn btn-success">Save</button>
    </form>
</div>
{% endblock %}

templates/user/result_display.html
{% extends "user/user_layout.html" %}

{% block content %}
{% load staticfiles %}
<div class="user-content">
    {% include '../result_display_layout.html' %}
</div>
{% endblock %}

templates/user/user_layout.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Create Online Exam for your students!!">
        <meta name="keywords" content="Create Online Exam, Objective exam, get result generated automatically">
        <meta name="author" content="Rajesh Upadhayaya">
        {% load staticfiles %}
    {#    {% collectstatic %}#}
        <link rel="icon" type="image/ico" href="{% static "/createonlineexam/images/favicon.ico" %}">
        <title>Create Online Exam</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <!-- Optional theme -->
        <link rel="stylesheet" href="{% static "/createonlineexam/css/bootstrap-theme.min.css" %}">
        <!--Modified personal css-->
        <link rel="stylesheet" type="text/css" href="{% static "/createonlineexam/css/style.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "/user/style.css" %}">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Crimson+Text:600' rel='stylesheet' type='text/css'>
    </head>

    <body>
    {% include 'user/navbar_user.html' %}

    <div class="row">
        <div class="col-sm-2">
            <div class="user-menu">
                <div class="profile-pic">
                    <img src="{% static 'media/' %}{{user.profile_pic}}" class="img-fluid">
                </div>
                <hr>

                {% if user.user_type is 1%}
                <div class="user-menu-option">
                    <ul>
                        <a href="{% url 'onlineexam:all_exams' %}"><li>Show all Exams</li></a>
                        <a href="{% url 'onlineexam:new_exam' %}"><li>Create New Exam</li></a>
                        <a href="{% url 'onlineexam:check_result' %}"><li>Check Result</li></a>

                    </ul>
                </div>
                {%endif%}

                {% if user.user_type is 2%}
                <div class="user-menu-option">
                    <ul>
                        <li><a href="#">My Exams</a></li>

                    </ul>
                </div>
                {%endif%}

            </div>

        </div>
        <div class="col-sm-10">

            {% block content %}
            {% endblock %}
        </div>
    </div>


    </body>

    <script scr="{% static "createonlineexam/js/jquery.lazyload.min.js" %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script src="{% static "createonlineexam/js/jquery.form.js" %}"></script>
    <script src="{% static "script.js" %}"></script>
    <!--validate script to validate form-->
<!--    <script src="{% static "createonlineexam/js/Validation.js" %}"></script>-->
<!--    <script src="{% static "createonlineexam/js/script.js" %}"></script>-->
<!--    <script src="{% static "createonlineexam/js/notify.js" %}"></script>-->
<!--    <script src="{% static "createonlineexam/js/paging.js" %}"></script>-->


    <script type="text/javascript">
        function goBack() {
            window.history.back();
        }

    </script>

    <a href="#create-exam" class="scrollToTop"><img src="{% static "createonlineexam/images/top.png" %}" height="40" width="40"></a>
    <footer class="text-center">

        <div id="footer" class="footer">

            <p>All Rights Reserved</p>
        </div>
    </footer>
</html>